<?php

/* config.template.html */
class __TwigTemplate_275e0ec4c6c070f514534cb0ac6c47dda9c55dc80b815fff42ceabed77a32af9 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        echo "<h1>Configuration</h1>

<p>There are 3 primary configuration files for Disco</p>
<ul class='list'>
    <li>
        <a href='https://github.com/discophp/project/blob/master/.config.php'>.config.php</a>
        <span>- Your local environments settings</span>
    </li>
    <li>.dev.config.php<span>- Your development environment settings. Will only attempt to be loaded if app is in DEV MODE ( <span class='variable'>APP_MODE=DEV</span> ).
        Any variables you have set in your <span class='path'>.dev.config.php</span> will override its production <span class='path'>.config.php</span> counterpart value.
        The <span class='path'>.dev.config.php</span> does not have to exist or be used while in <span class='variable'>DEV</span> MODE
    </span></li>
    <li>
        <a href='https://github.com/discophp/project/blob/master/.mail.config.php'>.mail.conf.php</a> 
        <span>- Your Email settings</span>
    </li>
</ul>


<hr>

<h2 class='mlarge-font'>.config.php - Your applications primary configuration file</h2>

<pre class='prettyprint'>
return Array(
    'URL'=>'localhost',

    'COMPOSER_PATH'=>'vendor',

    'TEMPLATE_EXTENSION'=>'.html',

    'APP_MODE'=>'DEV',
    'MAINTENANCE_MODE'=>'NO',

    'DB_HOST'=>'localhost',
    'DB_USER'=>'root',
    'DB_PASSWORD'=>'password',
    'DB_DB'=>'testdb',

    'MEMCACHE_HOST'=>'localhost',
    'MEMCACHE_PORT'=>'11211',

    'AES_KEY256'=>'8348515285f6d1e9826c5dd53ec8c404',

    'SHA512_SALT_LEAD'=>'18109d6d31ba',
    'SHA512_SALT_TAIL'=>'4ec0bf16dc2f'
 );
</pre>

<p>Most of these should be pretty self-explanatory.</p>
<ul class='list'>
    <li>\"URL\" <span>- The URL of your project ( somesite.com/ || sub.localhost/ )</span></li>
    <li>\"TEMPLATE_EXTENSION\" <span>- A default extension for your templates. Saves you from repeating yourself.</span></li>
    <li>\"APP_MODE\" <span>- The mode your application is running ( DEV || PROD )</span></li>
    <li>\"MAINTENANCE_MODE\" <span>- Whether or not your application is in MAINTENANCE_MODE ( YES || NO )</span></li>
    <li>\"COMPOSER_PATH\" <span>- Installation directory of Composer</span></li>
    <li>\"DB_*\" <span>- Set up your DB config options for MySQL.</span></li>
    <li>\"MEMCACHE_*\" <span>- Set up your Memcache Host and Port</span></li>
    <li>\"AES_KEY256\" <span>- This will be set to a 32 length value for you after install</span></li>
    <li>\"SHA512_SALT_*\" <span>- This will be set to a 12 length value for you after install</span></li>
</ul>

<div class='panel alert'>
    <p class='heading'>About the variable <span class='variable'>APP_MODE</span></p>
    <p>This controls what mode your application is running in.</p>
    <p>You can run in two different modes; <span class='variable'>DEV</span> or <span class='variable'>PROD</span></p>
    <p>When you are in <span class='variable'>DEV</span> mode your application will do these things differently:</p>
    <ul>
        <li>Send all emails to the email address set in the <span class='path'>.mail.config.php</span> file with the key <span class='variable'>DEV_MODE_SEND_TO</span></li>
        <li>If <span class='path'>.dev.config.php</span> exists, override the <span class='path'>.config.php</span> values with any of its values</li>
    </ul>
</div>

<div class='panel alert'>
    <p class='heading'>About the variable <span class='variable'>MAINTENANCE_MODE</span></p>
    <p>When this is set to <span class='variable'>YES</span> all requests to your application will result in a maintenance screen and zero of your application logic will be processed.
    The maintenance mode screen is generated by the result of calling the Closure function stored in <a href='http://github.com/discophp/project/blob/master/app/maintenance.php' target='_blank'>app/maintenance.php</a>.
    You can customize it to your liking (Don't forget you have access to all your Facades from within that Closure function).
    </p>
</div>


<p>You can set any variables in your <span class='path'>.config.php</span> files you want, they will be accessible through out your application via <span class='variable'>App::instance()->config['VAR']</span></p>

<hr>

<h3 class='mlarge-font'>.mail.config.php - Your email configuration file</h3>

<img src='/images/mail-config-php.png'>
<p>Set up your SMTP, TLS, and/or SSL email servers settings.</p>
<p>Set up your email addresses by replacing <span class='variable'>johns-email</span> with your defined key and and appropriate information.</p>
<p>You can add as many email addresses as you want to the <span class='path'>.mail.config.php<span> file.</p>
<p>Learn how to use the <a href='/docs/Email'>Email Facade</a>.</p>

<hr>

<h4 class='mlarge-font'>Configuring your Apache2 or Nginx Server to handle URL rewriting</h4>

<p class='heading'>For Apache2 Servers</p>

<p>Make sure you have the <span class='path'>rewrite module</span> enabled</p>

<p class='command'>sudo a2enmod rewrite</p>

<p class='heading'>.htaccess rules</p>
<pre class='prettyprint'>

    &lt;IFModule mod_rewrite.c&gt;

        RewriteEngine On

        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

    &lt;/IfModule&gt;

</pre>


<p class='heading'>For Nginx Servers</p>

<p>Add this directive to your sites configuration file</p>

<pre class='prettyprint'>

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

</pre>


";
    }

    public function getTemplateName()
    {
        return "config.template.html";
    }

    public function getDebugInfo()
    {
        return array (  19 => 1,);
    }
}
